version: '3'

env:
  PROJECT: 'git-cleaner'

tasks:
  build:
    desc: "Compile binary for supported platforms"
    cmds:
      - for: ['linux-x64', 'linux-arm64', 'darwin-arm64', 'darwin-x64']
        cmd: |
          echo "Compiling for {{.ITEM}}..."
          bun build \
            --compile \
            --target=bun-{{.ITEM}} \
            --minify \
            --sourcemap \
            ./cli.ts \
            --outfile ./dist/$PROJECT-{{.ITEM}}

  compress:
    desc: "Compress the binaries"
    cmds:
      - for: ['linux-x64', 'linux-arm64', 'darwin-arm64', 'darwin-x64']
        cmd: |
          echo "Compressing {{.ITEM}} binary..."
          tar -czvf ./dist/$PROJECT-{{.ITEM}}.tar.gz -C ./dist/ $PROJECT-{{.ITEM}}
