name: 🚀 Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: 💻 Checkout current pull-request revision code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.DEVOPS_USER_TOKEN }}

      - name: 🟢 Configure Bun on runner
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
        
      - name: 🔵 Install Task
        uses: arduino/setup-task@v2
  
      - name: 💼 Configure Git user
        run: |
          git config user.name "gbh-devops-bot"
          git config user.email "devops@gbh.com.do"

      - name: 📦 Install package dependencies using lockfile
        run: bun install --frozen-lockfile

      - name: 🔨 Compile binary for supported platforms
        run: |
          task build
          task compress

      - name: 🚀 Release a new version
        run: bun release-it --ci
        env:
          GITHUB_TOKEN: ${{ secrets.DEVOPS_USER_TOKEN }}
